ARG version
FROM almalinux:${version:-9}

# default version i have given as 9 , you can override the version in runtime/build time 
# command-----> docker build -t <image name>:v1 --build-arg version=8 .

ARG trainer=mamatha
ENV trainer="siva"
CMD [ "sleep", "100" ]  
